"""empty message

Revision ID: 4d66e63c2aa7
Revises: d56f120b5c15
Create Date: 2025-04-05 17:02:19.527821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d66e63c2aa7'
down_revision = 'd56f120b5c15'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('school', 'display_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('school', 'url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('school', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('school', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('school', 'headmaster',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('school', 'headmaster',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('school', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('school', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('school', 'url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('school', 'display_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
