"""empty message

Revision ID: 616d0f3aa9fc
Revises: d1749643403f
Create Date: 2025-04-05 17:52:40.213793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '616d0f3aa9fc'
down_revision = 'd1749643403f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('school', 'municipality_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('school', 'municipality_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
