"""empty message

Revision ID: 74b14885fb4c
Revises: 4d66e63c2aa7
Create Date: 2025-04-05 17:08:44.411179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74b14885fb4c'
down_revision = '4d66e63c2aa7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('school', 'visit_address_street',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('school', 'visit_address_postal_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('school', 'visit_address_locality',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('school', 'geo_lat',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('school', 'geo_long',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('school', 'geo_long',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('school', 'geo_lat',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('school', 'visit_address_locality',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('school', 'visit_address_postal_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('school', 'visit_address_street',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
