"""empty message

Revision ID: d1749643403f
Revises: 74b14885fb4c
Create Date: 2025-04-05 17:51:54.664463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1749643403f'
down_revision = '74b14885fb4c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('school', sa.Column('full_data', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('school', 'full_data')
    # ### end Alembic commands ###
